services:
  influxdb-mcp:
    build: .
    ports:
      - "5001:5001"
    environment:
      # Override these with your actual InfluxDB settings
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_TOKEN=mytoken
      - INFLUXDB_ORG=myorg
      - INFLUXDB_TIMEOUT=10000
    restart: unless-stopped

  # Optional: Include InfluxDB for complete stack testing
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped
    profiles:
      - with-influxdb

volumes:
  influxdb-data:
